// Named constants for the action strings AuditService.record() callers pass,
// so every call site spells the same event the same way. `action` itself
// stays a plain string on record() (not a strict union) so this list can
// grow without a schema/type change — these are a readability aid, not an
// enforced enum. Legacy rows created before this file existed keep their
// old "school.create"-style action strings forever; nothing here rewrites
// history.
export const AuditAction = {
  LOGIN: "LOGIN",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  TOTP_ENABLED: "TOTP_ENABLED",
  TOTP_DISABLED: "TOTP_DISABLED",
  TOTP_VERIFY_FAILED: "TOTP_VERIFY_FAILED",
  TOTP_RECOVERY_CODE_USED: "TOTP_RECOVERY_CODE_USED",

  STUDENT_CREATED: "STUDENT_CREATED",
  STUDENT_UPDATED: "STUDENT_UPDATED",
  STUDENT_ARCHIVED: "STUDENT_ARCHIVED",
  STUDENT_DELETED: "STUDENT_DELETED",
  STUDENT_IMPORTED: "STUDENT_IMPORTED",
  STUDENT_PORTAL_ACCOUNT_CREATED: "STUDENT_PORTAL_ACCOUNT_CREATED",
  STUDENT_PORTAL_PASSWORD_RESET: "STUDENT_PORTAL_PASSWORD_RESET",
  STUDENT_TRANSFERRED: "STUDENT_TRANSFERRED",

  TEACHER_CREATED: "TEACHER_CREATED",
  TEACHER_UPDATED: "TEACHER_UPDATED",
  TEACHER_DELETED: "TEACHER_DELETED",
  TEACHER_LOGIN_INVITED: "TEACHER_LOGIN_INVITED",
  TEACHER_LOGIN_INVITE_RESENT: "TEACHER_LOGIN_INVITE_RESENT",

  PARENT_DELETED: "PARENT_DELETED",
  PARENT_LOGIN_INVITED: "PARENT_LOGIN_INVITED",
  PARENT_PORTAL_PASSWORD_RESET: "PARENT_PORTAL_PASSWORD_RESET",

  ATTENDANCE_MARKED: "ATTENDANCE_MARKED",
  ATTENDANCE_DRAFT_SAVED: "ATTENDANCE_DRAFT_SAVED",

  RESULTS_ENTERED: "RESULTS_ENTERED",
  // A save that changed at least one ALREADY-recorded mark (or absence) —
  // distinct from first-time entry so corrections are easy to find.
  RESULTS_CORRECTED: "RESULTS_CORRECTED",
  RESULTS_APPROVED: "RESULTS_APPROVED",
  EXAM_PAPER_UPLOADED: "EXAM_PAPER_UPLOADED",
  RESULTS_SUBMITTED: "RESULTS_SUBMITTED",
  RESULTS_RETURNED: "RESULTS_RETURNED",
  RESULTS_RESUBMITTED: "RESULTS_RESUBMITTED",
  RESULTS_PUBLISHED: "RESULTS_PUBLISHED",
  RESULTS_UNPUBLISHED: "RESULTS_UNPUBLISHED",
  EXAM_SUBJECT_UPDATED: "EXAM_SUBJECT_UPDATED",
  EXAM_TERM_CHANGED: "EXAM_TERM_CHANGED",

  INVOICES_GENERATED: "INVOICES_GENERATED",
  PAYMENT_RECORDED: "PAYMENT_RECORDED",
  PAYMENT_REVERSED: "PAYMENT_REVERSED",
  CHARGES_GENERATED: "CHARGES_GENERATED",
  FEE_ADJUSTMENT_CREATED: "FEE_ADJUSTMENT_CREATED",
  ZAAD_SUBMITTED: "ZAAD_SUBMITTED",
  ZAAD_VERIFIED: "ZAAD_VERIFIED",
  ZAAD_REJECTED: "ZAAD_REJECTED",

  SALARY_CHANGED: "SALARY_CHANGED",
  STAFF_ADVANCE_ISSUED: "STAFF_ADVANCE_ISSUED",
  PAYSLIP_CREATED: "PAYSLIP_CREATED",
  PAYSLIP_CALCULATED: "PAYSLIP_CALCULATED",
  PAYSLIP_REVIEWED: "PAYSLIP_REVIEWED",
  PAYSLIP_APPROVED: "PAYSLIP_APPROVED",
  PAYSLIP_PAID: "PAYSLIP_PAID",

  EXPENSE_CREATED: "EXPENSE_CREATED",
  EXPENSE_APPROVED: "EXPENSE_APPROVED",
  EXPENSE_REJECTED: "EXPENSE_REJECTED",
  EXPENSE_PAID: "EXPENSE_PAID",

  TRANSFER_REQUESTED: "TRANSFER_REQUESTED",
  TRANSFER_APPROVED: "TRANSFER_APPROVED",
  TRANSFER_REJECTED: "TRANSFER_REJECTED",
  TRANSFER_CANCELLED: "TRANSFER_CANCELLED",
  // One admin with access to both schools requests-and-accepts many
  // students in a single action — see TransfersService.confirmBulkTransfer.
  // Distinct from TRANSFER_APPROVED (the normal two-admin flow) even
  // though the end result on each Transfer row is identical (EXECUTED).
  TRANSFER_BULK_COMPLETED: "TRANSFER_BULK_COMPLETED",

  PROMOTION_CONFIRMED: "PROMOTION_CONFIRMED",
  STUDENT_RETAINED: "STUDENT_RETAINED",
  PRIMARY_COMPLETION: "PRIMARY_COMPLETION",
  SECONDARY_GRADUATION: "SECONDARY_GRADUATION",
  FORM_1_TRANSITION: "FORM_1_TRANSITION",

  ACADEMIC_YEAR_DELETED: "ACADEMIC_YEAR_DELETED",
  CLASS_BULK_TRANSFERRED: "CLASS_BULK_TRANSFERRED",

  SCHOOL_CREATED: "SCHOOL_CREATED",
  SCHOOL_DELETED: "SCHOOL_DELETED",
  SCHOOL_ADMIN_INVITED: "SCHOOL_ADMIN_INVITED",
  SCHOOL_LOGO_CHANGED: "SCHOOL_LOGO_CHANGED",
  SCHOOL_LOGO_REMOVED: "SCHOOL_LOGO_REMOVED",

  DEPARTMENT_CREATED: "DEPARTMENT_CREATED",
  DEPARTMENT_UPDATED: "DEPARTMENT_UPDATED",
  STAFF_CREATED: "STAFF_CREATED",
  STAFF_UPDATED: "STAFF_UPDATED",
  STAFF_DELETED: "STAFF_DELETED",
  STAFF_ASSIGNED_TO_SCHOOL: "STAFF_ASSIGNED_TO_SCHOOL",
  STAFF_ASSIGNMENT_DEACTIVATED: "STAFF_ASSIGNMENT_DEACTIVATED",
  LEAVE_REQUESTED: "LEAVE_REQUESTED",
  LEAVE_APPROVED: "LEAVE_APPROVED",
  LEAVE_REJECTED: "LEAVE_REJECTED",
  STAFF_ATTENDANCE_MARKED: "STAFF_ATTENDANCE_MARKED",
} as const;

// Named "...Name" to avoid any confusion with the NestJS AuditModule class
// in ./audit.module.ts — this is just a set of string constants.
export const AuditModuleName = {
  AUTHENTICATION: "Authentication",
  STUDENTS: "Students",
  TEACHERS: "Teachers",
  PARENTS: "Parents",
  ATTENDANCE: "Attendance",
  RESULTS: "Results",
  FINANCE: "Finance",
  STAFF: "Staff",
  PAYROLL: "Payroll",
  TRANSFERS: "Transfers",
  PROMOTIONS: "Promotions",
  STUDENT_LIFECYCLE: "Student Lifecycle",
  ACADEMIC: "Academic",
  SCHOOL: "School",
} as const;
